<?php
/**
 * reset-password.php — standalone password reset page.
 * Linked from emails generated by forgot_password and create_user.
 */
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/functions.php';

$token   = trim($_GET['token'] ?? $_POST['token'] ?? '');
$error   = '';
$success = false;

// Validate token format upfront
$validFormat = (strlen($token) === 64 && ctype_xdigit($token));

// On POST: attempt the password reset
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $validFormat) {
    $password  = $_POST['password']  ?? '';
    $password2 = $_POST['password2'] ?? '';

    if (strlen($password) < 6) {
        $error = 'Password must be at least 6 characters.';
    } elseif ($password !== $password2) {
        $error = 'Passwords do not match.';
    } else {
        // Use the api reset_password logic directly
        $db   = getDB();
        $stmt = $db->prepare(
            'SELECT pr.user_id, pr.token, pr.expires_at
             FROM password_resets pr WHERE pr.token = ?'
        );
        $stmt->execute([$token]);
        $row = $stmt->fetch();

        if (!$row || !hash_equals($row['token'], $token)) {
            $error = 'Invalid or expired reset link. Please request a new one.';
        } elseif (strtotime($row['expires_at']) < time()) {
            $db->prepare('DELETE FROM password_resets WHERE user_id = ?')->execute([$row['user_id']]);
            $error = 'This reset link has expired. Please request a new one.';
        } else {
            $hash = password_hash($password, PASSWORD_DEFAULT);
            $db->prepare('UPDATE users SET password_hash = ? WHERE id = ?')->execute([$hash, $row['user_id']]);
            $db->prepare('DELETE FROM password_resets WHERE user_id = ?')->execute([$row['user_id']]);
            clearLoginAttempts(getClientIP());
            $success = true;
        }
    }
} elseif ($validFormat && $_SERVER['REQUEST_METHOD'] === 'GET') {
    // Pre-validate: check if token exists and is not expired before showing the form
    $db   = getDB();
    $stmt = $db->prepare('SELECT expires_at FROM password_resets WHERE token = ?');
    $stmt->execute([$token]);
    $row = $stmt->fetch();
    if (!$row) {
        $error = 'Invalid or expired reset link. Please request a new one.';
    } elseif (strtotime($row['expires_at']) < time()) {
        $db->prepare('DELETE FROM password_resets WHERE token = ?')->execute([$token]);
        $error = 'This reset link has expired. Please request a new one.';
    }
} elseif (!$validFormat) {
    $error = 'Invalid reset link.';
}

$appName = SMTP_FROM_NAME;
$homeUrl = SITE_URL . '/index.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= htmlspecialchars($appName) ?> — Set Password</title>
<style>
  *, *::before, *::after { box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; background: #1a1a1a; color: #fffbf5; min-height: 100vh; display: flex; align-items: center; justify-content: center; margin: 0; padding: 24px; }
  .card { background: #222222; border: 1px solid #383838; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,.40); padding: 36px 32px; width: 100%; max-width: 400px; }
  .logo { font-size: 22px; font-weight: 800; color: #4A90E2; margin-bottom: 6px; }
  h1 { font-size: 18px; font-weight: 700; color: #fffbf5; margin: 0 0 20px; }
  label { display: block; font-size: 13px; font-weight: 600; color: #fffbf5; margin-bottom: 5px; }
  input[type=password] { width: 100%; padding: 9px 12px; border: 1px solid #484848; border-radius: 7px; font-size: 14px; outline: none; transition: border-color .15s; margin-bottom: 14px; background: #2a2a2a; color: #fffbf5; }
  input[type=password]:focus { border-color: #4A90E2; box-shadow: 0 0 0 3px rgba(74,144,226,.20); }
  button { width: 100%; padding: 10px; background: #4A90E2; color: #fff; border: none; border-radius: 7px; font-size: 15px; font-weight: 600; cursor: pointer; margin-top: 4px; }
  button:hover { background: #2f6db5; }
  .alert { padding: 10px 14px; border-radius: 7px; font-size: 13px; margin-bottom: 16px; }
  .alert-error { background: rgba(181,43,43,0.20); border: 1px solid #b52b2b; color: #f4a0a0; }
  .alert-success { background: rgba(45,106,79,0.20); border: 1px solid #2d6a4f; color: #74c69d; }
  .back { margin-top: 18px; text-align: center; font-size: 13px; color: #909090; }
  .back a { color: #4A90E2; text-decoration: none; font-weight: 600; }
  .back a:hover { text-decoration: underline; }
  .hint { font-size: 12px; color: #909090; margin-top: -10px; margin-bottom: 14px; }
</style>
</head>
<body>
<div class="card">
  <div class="logo"><?= htmlspecialchars($appName) ?></div>

  <?php if ($success): ?>
    <h1>Password set!</h1>
    <div class="alert alert-success">Your password has been updated. You can now log in.</div>
    <div class="back"><a href="<?= htmlspecialchars($homeUrl) ?>">← Go to the app</a></div>

  <?php elseif ($error): ?>
    <h1>Reset link problem</h1>
    <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
    <div class="back"><a href="<?= htmlspecialchars($homeUrl) ?>">← Back to login</a></div>

  <?php else: ?>
    <h1>Set your password</h1>
    <form method="post">
      <input type="hidden" name="token" value="<?= htmlspecialchars($token) ?>">
      <label for="password">New password</label>
      <input type="password" id="password" name="password" required minlength="6" autofocus autocomplete="new-password">
      <p class="hint">At least 6 characters</p>
      <label for="password2">Confirm password</label>
      <input type="password" id="password2" name="password2" required autocomplete="new-password">
      <button type="submit">Set Password</button>
    </form>
    <div class="back"><a href="<?= htmlspecialchars($homeUrl) ?>">← Back to login</a></div>
  <?php endif; ?>
</div>
</body>
</html>
